# Generated by Django 2.2 on 2019-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(help_text='Famous quote', max_length=250)),
                ('attribute', models.CharField(help_text='Who said that?', max_length=50)),
            ],
            options={
                'ordering': ['quote'],
            },
        ),
    ]
